spring:
  datasource:
    url: jdbc:postgresql://localhost:2020/flashcards
    username: postgres
    password: 12345
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:db.changelog-master.xml

jwt:
  secret: LMPpUV21EQFiqgqoMnLGNBhEsGDknJMGx5mHnwPlvOvCb0e2mjwvZASYE3YuZ9iypwerj7wPm8YUOFhP/85gew==
  expirationMs: 86400000